package com.pkrandomizerweb;

import com.dabomstew.pkrandom.Settings;
import com.dabomstew.pkrandom.pokemon.GenRestrictions;
import org.json.JSONObject;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

/**
 * Generated by java-shim/generate-shim.mjs from settings-schema.json — do
 * not hand-edit. The inverse of {@link SettingsBuilder}: reads an existing
 * binary .rnqs settings file via the real {@link Settings#read(FileInputStream)}
 * (the same format produced by the desktop app's "Make Preset" / by our own
 * SettingsBuilder) and prints it as JSON shaped by settings-schema.json, so
 * the web form can be prefilled from an uploaded settings file.
 *
 * Usage: java -cp PokeRandoZX.jar:settings-shim.jar com.pkrandomizerweb.SettingsReader <input.rnqs>
 * Prints the JSON payload to stdout.
 */
public class SettingsReader {

    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("Usage: SettingsReader <input.rnqs>");
            System.exit(1);
        }
        String inputSettingsPath = args[0];

        try (FileInputStream in = new FileInputStream(new File(inputSettingsPath))) {
            Settings settings = Settings.read(in);
            JSONObject json = new JSONObject();
            dump(settings, json);
            System.out.println(json.toString());
        } catch (IOException e) {
            System.err.println("ERROR: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } catch (RuntimeException e) {
            System.err.println("ERROR: invalid or unreadable settings file: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    private static void dump(Settings settings, JSONObject json) {
        // romName -- ROM display-name metadata written into the settings string; not itself a randomization toggle. Inclu
        json.put("romName", settings.getRomName());

        // currentRestrictions -- Takes a GenRestrictions object (see top-level 'genRestrictions' section). Only meaningful when limit
        {
            GenRestrictions gr = settings.getCurrentRestrictions();
            org.json.JSONObject grJson = new org.json.JSONObject();
            grJson.put("allow_gen1", gr != null && gr.allow_gen1);
            grJson.put("allow_gen2", gr != null && gr.allow_gen2);
            grJson.put("allow_gen3", gr != null && gr.allow_gen3);
            grJson.put("allow_gen4", gr != null && gr.allow_gen4);
            grJson.put("allow_gen5", gr != null && gr.allow_gen5);
            grJson.put("allow_gen6", gr != null && gr.allow_gen6);
            grJson.put("allow_gen7", gr != null && gr.allow_gen7);
            grJson.put("allow_evolutionary_relatives", gr != null && gr.allow_evolutionary_relatives);
            json.put("currentRestrictions", grJson);
        }

        // currentMiscTweaks -- Takes an int bitmask. See top-level 'miscTweaks' section for each individual tweak's bit value; the 
        {
            int bits = settings.getCurrentMiscTweaks();
            org.json.JSONArray tweaksArr = new org.json.JSONArray();
            if ((bits & 1) != 0) tweaksArr.put("BW_EXP_PATCH");
            if ((bits & 2) != 0) tweaksArr.put("NERF_X_ACCURACY");
            if ((bits & 4) != 0) tweaksArr.put("FIX_CRIT_RATE");
            if ((bits & 8) != 0) tweaksArr.put("FASTEST_TEXT");
            if ((bits & 16) != 0) tweaksArr.put("RUNNING_SHOES_INDOORS");
            if ((bits & 32) != 0) tweaksArr.put("RANDOMIZE_PC_POTION");
            if ((bits & 64) != 0) tweaksArr.put("ALLOW_PIKACHU_EVOLUTION");
            if ((bits & 128) != 0) tweaksArr.put("NATIONAL_DEX_AT_START");
            if ((bits & 256) != 0) tweaksArr.put("UPDATE_TYPE_EFFECTIVENESS");
            if ((bits & 512) != 0) tweaksArr.put("FORCE_CHALLENGE_MODE");
            if ((bits & 1024) != 0) tweaksArr.put("LOWER_CASE_POKEMON_NAMES");
            if ((bits & 2048) != 0) tweaksArr.put("RANDOMIZE_CATCHING_TUTORIAL");
            if ((bits & 4096) != 0) tweaksArr.put("BAN_LUCKY_EGG");
            if ((bits & 8192) != 0) tweaksArr.put("NO_FREE_LUCKY_EGG");
            if ((bits & 16384) != 0) tweaksArr.put("BAN_BIG_MANIAC_ITEMS");
            if ((bits & 32768) != 0) tweaksArr.put("SOS_BATTLES_FOR_ALL");
            if ((bits & 65536) != 0) tweaksArr.put("BALANCE_STATIC_LEVELS");
            if ((bits & 131072) != 0) tweaksArr.put("RETAIN_ALT_FORMES");
            if ((bits & 262144) != 0) tweaksArr.put("RUN_WITHOUT_RUNNING_SHOES");
            if ((bits & 524288) != 0) tweaksArr.put("FASTER_HP_AND_EXP_BARS");
            if ((bits & 1048576) != 0) tweaksArr.put("FAST_DISTORTION_WORLD");
            if ((bits & 2097152) != 0) tweaksArr.put("UPDATE_ROTOM_FORME_TYPING");
            if ((bits & 4194304) != 0) tweaksArr.put("DISABLE_LOW_HP_MUSIC");
            json.put("currentMiscTweaks", tweaksArr);
        }

        // updateMoves -- Update move data (power/accuracy/PP/etc) to match a later generation's values, up to updateMovesToGe
        json.put("updateMoves", settings.isUpdateMoves());

        // updateMovesLegacy -- Legacy/older variant of the move-data-update feature, kept for backward compatibility with old setti
        json.put("updateMovesLegacy", settings.isUpdateMovesLegacy());

        // updateMovesToGeneration -- Generation number (e.g. 1-7) to update move data to; only relevant when updateMoves is true.
        json.put("updateMovesToGeneration", settings.getUpdateMovesToGeneration());

        // dualTypeOnly
        json.put("dualTypeOnly", settings.isDualTypeOnly());

        // changeImpossibleEvolutions
        json.put("changeImpossibleEvolutions", settings.isChangeImpossibleEvolutions());

        // makeEvolutionsEasier
        json.put("makeEvolutionsEasier", settings.isMakeEvolutionsEasier());

        // removeTimeBasedEvolutions
        json.put("removeTimeBasedEvolutions", settings.isRemoveTimeBasedEvolutions());

        // evosAllowAltFormes -- Declared alongside the other Evolutions-tab fields in Settings.java, but its setter is interleaved w
        json.put("evosAllowAltFormes", settings.isEvosAllowAltFormes());

        // raceMode
        json.put("raceMode", settings.isRaceMode());

        // banIrregularAltFormes
        json.put("banIrregularAltFormes", settings.isBanIrregularAltFormes());

        // blockBrokenMoves -- Convenience setter: internally sets blockBrokenMovesetMoves, blockBrokenTMMoves, and blockBrokenTuto
        // blockBrokenMoves intentionally skipped — write-only convenience setter, no getter (see NO_GETTER_FIELDS)

        // limitPokemon -- Enables the generation-restriction pool defined by currentRestrictions (GenRestrictions).
        json.put("limitPokemon", settings.isLimitPokemon());

        // baseStatisticsMod -- Java setter signature is `setBaseStatisticsMod(boolean... bools)`. Internally it calls Settings.getE
        json.put("baseStatisticsMod", settings.getBaseStatisticsMod().name());

        // baseStatsFollowEvolutions
        json.put("baseStatsFollowEvolutions", settings.isBaseStatsFollowEvolutions());

        // baseStatsFollowMegaEvolutions
        json.put("baseStatsFollowMegaEvolutions", settings.isBaseStatsFollowMegaEvolutions());

        // assignEvoStatsRandomly
        json.put("assignEvoStatsRandomly", settings.isAssignEvoStatsRandomly());

        // updateBaseStats
        json.put("updateBaseStats", settings.isUpdateBaseStats());

        // updateBaseStatsToGeneration -- Generation number to update base stats to; only relevant when updateBaseStats is true.
        json.put("updateBaseStatsToGeneration", settings.getUpdateBaseStatsToGeneration());

        // standardizeEXPCurves
        json.put("standardizeEXPCurves", settings.isStandardizeEXPCurves());

        // selectedEXPCurve -- Takes the ExpCurve enum directly (not varargs booleans) - com.dabomstew.pkrandom.pokemon.ExpCurve, n
        json.put("selectedEXPCurve", settings.getSelectedEXPCurve().name());

        // expCurveMod -- Controls which Pokemon (legendaries only / strong legendaries / all) get standardizeEXPCurves' selec
        json.put("expCurveMod", settings.getExpCurveMod().name());

        // abilitiesMod -- Java setter signature is `setAbilitiesMod(boolean... bools)`. Internally it calls Settings.getEnum(A
        json.put("abilitiesMod", settings.getAbilitiesMod().name());

        // allowWonderGuard
        json.put("allowWonderGuard", settings.isAllowWonderGuard());

        // abilitiesFollowEvolutions
        json.put("abilitiesFollowEvolutions", settings.isAbilitiesFollowEvolutions());

        // abilitiesFollowMegaEvolutions
        json.put("abilitiesFollowMegaEvolutions", settings.isAbilitiesFollowMegaEvolutions());

        // banTrappingAbilities
        json.put("banTrappingAbilities", settings.isBanTrappingAbilities());

        // banNegativeAbilities
        json.put("banNegativeAbilities", settings.isBanNegativeAbilities());

        // banBadAbilities
        json.put("banBadAbilities", settings.isBanBadAbilities());

        // weighDuplicateAbilitiesTogether
        json.put("weighDuplicateAbilitiesTogether", settings.isWeighDuplicateAbilitiesTogether());

        // ensureTwoAbilities
        json.put("ensureTwoAbilities", settings.isEnsureTwoAbilities());

        // startersMod -- Java setter signature is `setStartersMod(boolean... bools)`. Internally it calls Settings.getEnum(St
        json.put("startersMod", settings.getStartersMod().name());

        // customStarters -- Takes int[3] (one 1-indexed Pokemon-list position per starter slot). Only relevant when startersMod 
        {
            int[] customStartersVals = settings.getCustomStarters();
            org.json.JSONArray customStartersArr = new org.json.JSONArray();
            for (int v : customStartersVals) customStartersArr.put(v);
            json.put("customStarters", customStartersArr);
        }

        // randomizeStartersHeldItems
        json.put("randomizeStartersHeldItems", settings.isRandomizeStartersHeldItems());

        // banBadRandomStarterHeldItems
        json.put("banBadRandomStarterHeldItems", settings.isBanBadRandomStarterHeldItems());

        // allowStarterAltFormes
        json.put("allowStarterAltFormes", settings.isAllowStarterAltFormes());

        // typesMod -- Java setter signature is `setTypesMod(boolean... bools)`. Internally it calls Settings.getEnum(Types
        json.put("typesMod", settings.getTypesMod().name());

        // typesFollowMegaEvolutions
        json.put("typesFollowMegaEvolutions", settings.isTypesFollowMegaEvolutions());

        // evolutionsMod -- Java setter signature is `setEvolutionsMod(boolean... bools)`. Internally it calls Settings.getEnum(
        json.put("evolutionsMod", settings.getEvolutionsMod().name());

        // evosSimilarStrength
        json.put("evosSimilarStrength", settings.isEvosSimilarStrength());

        // evosSameTyping
        json.put("evosSameTyping", settings.isEvosSameTyping());

        // evosMaxThreeStages
        json.put("evosMaxThreeStages", settings.isEvosMaxThreeStages());

        // evosForceChange
        json.put("evosForceChange", settings.isEvosForceChange());

        // randomizeMovePowers
        json.put("randomizeMovePowers", settings.isRandomizeMovePowers());

        // randomizeMoveAccuracies
        json.put("randomizeMoveAccuracies", settings.isRandomizeMoveAccuracies());

        // randomizeMovePPs
        json.put("randomizeMovePPs", settings.isRandomizeMovePPs());

        // randomizeMoveTypes
        json.put("randomizeMoveTypes", settings.isRandomizeMoveTypes());

        // randomizeMoveCategory -- Only applicable to ROMs whose RomHandler reports hasPhysicalSpecialSplit() == true; the desktop app 
        json.put("randomizeMoveCategory", settings.isRandomizeMoveCategory());

        // movesetsMod -- Java setter signature is `setMovesetsMod(boolean... bools)`. Internally it calls Settings.getEnum(Mo
        json.put("movesetsMod", settings.getMovesetsMod().name());

        // startWithGuaranteedMoves
        json.put("startWithGuaranteedMoves", settings.isStartWithGuaranteedMoves());

        // guaranteedMoveCount -- Number of guaranteed starting moves; GUI range is 2-4. Only relevant when startWithGuaranteedMoves i
        json.put("guaranteedMoveCount", settings.getGuaranteedMoveCount());

        // reorderDamagingMoves
        json.put("reorderDamagingMoves", settings.isReorderDamagingMoves());

        // movesetsForceGoodDamaging
        json.put("movesetsForceGoodDamaging", settings.isMovesetsForceGoodDamaging());

        // movesetsGoodDamagingPercent -- Percent (0-100) of a Pokemon's moveset that should be 'good damaging' moves; only relevant when move
        json.put("movesetsGoodDamagingPercent", settings.getMovesetsGoodDamagingPercent());

        // blockBrokenMovesetMoves -- Also settable in bulk via the General Options 'blockBrokenMoves' convenience setter.
        json.put("blockBrokenMovesetMoves", settings.isBlockBrokenMovesetMoves());

        // evolutionMovesForAll
        json.put("evolutionMovesForAll", settings.isEvolutionMovesForAll());

        // trainersMod -- Java setter signature is `setTrainersMod(boolean... bools)`. Internally it calls Settings.getEnum(Tr
        json.put("trainersMod", settings.getTrainersMod().name());

        // rivalCarriesStarterThroughout
        json.put("rivalCarriesStarterThroughout", settings.isRivalCarriesStarterThroughout());

        // trainersUsePokemonOfSimilarStrength
        json.put("trainersUsePokemonOfSimilarStrength", settings.isTrainersUsePokemonOfSimilarStrength());

        // trainersMatchTypingDistribution
        json.put("trainersMatchTypingDistribution", settings.isTrainersMatchTypingDistribution());

        // trainersBlockLegendaries
        json.put("trainersBlockLegendaries", settings.isTrainersBlockLegendaries());

        // trainersEnforceDistribution -- NOTE: Java setter uses a fluent/builder signature `public Settings setTrainersEnforceDistribution(bo
        json.put("trainersEnforceDistribution", settings.isTrainersEnforceDistribution());

        // trainersEnforceMainPlaythrough -- NOTE: Java setter uses a fluent/builder signature `public Settings setTrainersEnforceMainPlaythrough
        json.put("trainersEnforceMainPlaythrough", settings.isTrainersEnforceMainPlaythrough());

        // trainersBlockEarlyWonderGuard
        json.put("trainersBlockEarlyWonderGuard", settings.isTrainersBlockEarlyWonderGuard());

        // randomizeTrainerNames
        json.put("randomizeTrainerNames", settings.isRandomizeTrainerNames());

        // randomizeTrainerClassNames
        json.put("randomizeTrainerClassNames", settings.isRandomizeTrainerClassNames());

        // trainersForceFullyEvolved
        json.put("trainersForceFullyEvolved", settings.isTrainersForceFullyEvolved());

        // trainersForceFullyEvolvedLevel -- Minimum level threshold; only relevant when trainersForceFullyEvolved is true.
        json.put("trainersForceFullyEvolvedLevel", settings.getTrainersForceFullyEvolvedLevel());

        // trainersLevelModified
        json.put("trainersLevelModified", settings.isTrainersLevelModified());

        // trainersLevelModifier -- Percent modifier, range -50..50. Only relevant when trainersLevelModified is true.
        json.put("trainersLevelModifier", settings.getTrainersLevelModifier());

        // eliteFourUniquePokemonNumber -- Range 0-2 (packed into 3 bits alongside minimumCatchRateLevel in the settings byte format).
        json.put("eliteFourUniquePokemonNumber", settings.getEliteFourUniquePokemonNumber());

        // allowTrainerAlternateFormes
        json.put("allowTrainerAlternateFormes", settings.isAllowTrainerAlternateFormes());

        // swapTrainerMegaEvos
        json.put("swapTrainerMegaEvos", settings.isSwapTrainerMegaEvos());

        // additionalBossTrainerPokemon -- Parameter name in Java is 'additional'. Number of extra Pokemon to add to boss trainers' teams.
        json.put("additionalBossTrainerPokemon", settings.getAdditionalBossTrainerPokemon());

        // additionalImportantTrainerPokemon -- Parameter name in Java is 'additional'. Number of extra Pokemon to add to important trainers' teams.
        json.put("additionalImportantTrainerPokemon", settings.getAdditionalImportantTrainerPokemon());

        // additionalRegularTrainerPokemon -- Parameter name in Java is 'additional'. Number of extra Pokemon to add to regular trainers' teams.
        json.put("additionalRegularTrainerPokemon", settings.getAdditionalRegularTrainerPokemon());

        // randomizeHeldItemsForBossTrainerPokemon -- Java parameter name is 'bossTrainers'.
        json.put("randomizeHeldItemsForBossTrainerPokemon", settings.isRandomizeHeldItemsForBossTrainerPokemon());

        // randomizeHeldItemsForImportantTrainerPokemon -- Java parameter name is 'importantTrainers'.
        json.put("randomizeHeldItemsForImportantTrainerPokemon", settings.isRandomizeHeldItemsForImportantTrainerPokemon());

        // randomizeHeldItemsForRegularTrainerPokemon -- Java parameter name is 'regularTrainers'.
        json.put("randomizeHeldItemsForRegularTrainerPokemon", settings.isRandomizeHeldItemsForRegularTrainerPokemon());

        // consumableItemsOnlyForTrainerPokemon -- Field name (consumableItemsOnlyForTrainerPokemon) differs from the setter name (setConsumableItemsOn
        json.put("consumableItemsOnlyForTrainerPokemon", settings.isConsumableItemsOnlyForTrainers());

        // sensibleItemsOnlyForTrainerPokemon -- Field name (sensibleItemsOnlyForTrainerPokemon) differs from the setter name (setSensibleItemsOnlyFo
        json.put("sensibleItemsOnlyForTrainerPokemon", settings.isSensibleItemsOnlyForTrainers());

        // highestLevelOnlyGetsItemsForTrainerPokemon -- Field name (highestLevelOnlyGetsItemsForTrainerPokemon) differs from the setter name (setHighestLeve
        json.put("highestLevelOnlyGetsItemsForTrainerPokemon", settings.isHighestLevelGetsItemsForTrainers());

        // doubleBattleMode
        json.put("doubleBattleMode", settings.isDoubleBattleMode());

        // shinyChance -- Despite the boolean type this represents an 'increased shiny chance' toggle, not a literal chance va
        json.put("shinyChance", settings.isShinyChance());

        // betterTrainerMovesets
        json.put("betterTrainerMovesets", settings.isBetterTrainerMovesets());

        // wildPokemonMod -- Java setter signature is `setWildPokemonMod(boolean... bools)`. Internally it calls Settings.getEnum
        json.put("wildPokemonMod", settings.getWildPokemonMod().name());

        // wildPokemonRestrictionMod -- Java setter signature is `setWildPokemonRestrictionMod(boolean... bools)`. Internally it calls Setti
        json.put("wildPokemonRestrictionMod", settings.getWildPokemonRestrictionMod().name());

        // useTimeBasedEncounters
        json.put("useTimeBasedEncounters", settings.isUseTimeBasedEncounters());

        // blockWildLegendaries
        json.put("blockWildLegendaries", settings.isBlockWildLegendaries());

        // useMinimumCatchRate
        json.put("useMinimumCatchRate", settings.isUseMinimumCatchRate());

        // minimumCatchRateLevel -- Range roughly 1-5 (GUI slider); only relevant when useMinimumCatchRate is true.
        json.put("minimumCatchRateLevel", settings.getMinimumCatchRateLevel());

        // randomizeWildPokemonHeldItems
        json.put("randomizeWildPokemonHeldItems", settings.isRandomizeWildPokemonHeldItems());

        // banBadRandomWildPokemonHeldItems
        json.put("banBadRandomWildPokemonHeldItems", settings.isBanBadRandomWildPokemonHeldItems());

        // balanceShakingGrass
        json.put("balanceShakingGrass", settings.isBalanceShakingGrass());

        // wildLevelsModified
        json.put("wildLevelsModified", settings.isWildLevelsModified());

        // wildLevelModifier -- Percent modifier, range -50..50. Only relevant when wildLevelsModified is true.
        json.put("wildLevelModifier", settings.getWildLevelModifier());

        // allowWildAltFormes
        json.put("allowWildAltFormes", settings.isAllowWildAltFormes());

        // staticPokemonMod -- Java setter signature is `setStaticPokemonMod(boolean... bools)`. Internally it calls Settings.getEn
        json.put("staticPokemonMod", settings.getStaticPokemonMod().name());

        // limitMainGameLegendaries -- Field is declared in Settings.java alongside the Starter Pokemon fields, but its setter is placed in
        json.put("limitMainGameLegendaries", settings.isLimitMainGameLegendaries());

        // limit600 -- Field is declared in Settings.java alongside the Starter Pokemon fields, but its setter is placed in
        json.put("limit600", settings.isLimit600());

        // allowStaticAltFormes
        json.put("allowStaticAltFormes", settings.isAllowStaticAltFormes());

        // swapStaticMegaEvos
        json.put("swapStaticMegaEvos", settings.isSwapStaticMegaEvos());

        // staticLevelModified
        json.put("staticLevelModified", settings.isStaticLevelModified());

        // staticLevelModifier -- Percent modifier, range -50..50. Only relevant when staticLevelModified is true.
        json.put("staticLevelModifier", settings.getStaticLevelModifier());

        // correctStaticMusic
        json.put("correctStaticMusic", settings.isCorrectStaticMusic());

        // tmsMod -- Java setter signature is `setTmsMod(boolean... bools)`. Internally it calls Settings.getEnum(TMsMod.
        json.put("tmsMod", settings.getTmsMod().name());

        // tmLevelUpMoveSanity
        json.put("tmLevelUpMoveSanity", settings.isTmLevelUpMoveSanity());

        // keepFieldMoveTMs
        json.put("keepFieldMoveTMs", settings.isKeepFieldMoveTMs());

        // fullHMCompat
        json.put("fullHMCompat", settings.isFullHMCompat());

        // tmsForceGoodDamaging
        json.put("tmsForceGoodDamaging", settings.isTmsForceGoodDamaging());

        // tmsGoodDamagingPercent -- Percent (0-100); only relevant when tmsForceGoodDamaging is true.
        json.put("tmsGoodDamagingPercent", settings.getTmsGoodDamagingPercent());

        // blockBrokenTMMoves -- Also settable in bulk via the General Options 'blockBrokenMoves' convenience setter.
        json.put("blockBrokenTMMoves", settings.isBlockBrokenTMMoves());

        // tmsHmsCompatibilityMod -- Java setter signature is `setTmsHmsCompatibilityMod(boolean... bools)`. Internally it calls Settings
        json.put("tmsHmsCompatibilityMod", settings.getTmsHmsCompatibilityMod().name());

        // tmsFollowEvolutions
        json.put("tmsFollowEvolutions", settings.isTmsFollowEvolutions());

        // moveTutorMovesMod -- Only applicable to ROMs that support move tutors (Gen 3 Emerald/FRLG onward). Java setter signature 
        json.put("moveTutorMovesMod", settings.getMoveTutorMovesMod().name());

        // tutorLevelUpMoveSanity
        json.put("tutorLevelUpMoveSanity", settings.isTutorLevelUpMoveSanity());

        // keepFieldMoveTutors
        json.put("keepFieldMoveTutors", settings.isKeepFieldMoveTutors());

        // tutorsForceGoodDamaging
        json.put("tutorsForceGoodDamaging", settings.isTutorsForceGoodDamaging());

        // tutorsGoodDamagingPercent -- Percent (0-100); only relevant when tutorsForceGoodDamaging is true.
        json.put("tutorsGoodDamagingPercent", settings.getTutorsGoodDamagingPercent());

        // blockBrokenTutorMoves -- Also settable in bulk via the General Options 'blockBrokenMoves' convenience setter.
        json.put("blockBrokenTutorMoves", settings.isBlockBrokenTutorMoves());

        // moveTutorsCompatibilityMod -- Java setter signature is `setMoveTutorsCompatibilityMod(boolean... bools)`. Internally it calls Sett
        json.put("moveTutorsCompatibilityMod", settings.getMoveTutorsCompatibilityMod().name());

        // tutorFollowEvolutions
        json.put("tutorFollowEvolutions", settings.isTutorFollowEvolutions());

        // inGameTradesMod -- Java setter signature is `setInGameTradesMod(boolean... bools)`. Internally it calls Settings.getEnu
        json.put("inGameTradesMod", settings.getInGameTradesMod().name());

        // randomizeInGameTradesNicknames
        json.put("randomizeInGameTradesNicknames", settings.isRandomizeInGameTradesNicknames());

        // randomizeInGameTradesOTs
        json.put("randomizeInGameTradesOTs", settings.isRandomizeInGameTradesOTs());

        // randomizeInGameTradesIVs
        json.put("randomizeInGameTradesIVs", settings.isRandomizeInGameTradesIVs());

        // randomizeInGameTradesItems
        json.put("randomizeInGameTradesItems", settings.isRandomizeInGameTradesItems());

        // fieldItemsMod -- Java setter signature is `setFieldItemsMod(boolean... bools)`. Internally it calls Settings.getEnum(
        json.put("fieldItemsMod", settings.getFieldItemsMod().name());

        // banBadRandomFieldItems
        json.put("banBadRandomFieldItems", settings.isBanBadRandomFieldItems());

        // shopItemsMod -- Java setter signature is `setShopItemsMod(boolean... bools)`. Internally it calls Settings.getEnum(S
        json.put("shopItemsMod", settings.getShopItemsMod().name());

        // banBadRandomShopItems
        json.put("banBadRandomShopItems", settings.isBanBadRandomShopItems());

        // banRegularShopItems
        json.put("banRegularShopItems", settings.isBanRegularShopItems());

        // banOPShopItems
        json.put("banOPShopItems", settings.isBanOPShopItems());

        // balanceShopPrices
        json.put("balanceShopPrices", settings.isBalanceShopPrices());

        // guaranteeEvolutionItems
        json.put("guaranteeEvolutionItems", settings.isGuaranteeEvolutionItems());

        // guaranteeXItems
        json.put("guaranteeXItems", settings.isGuaranteeXItems());

        // pickupItemsMod -- Java setter signature is `setPickupItemsMod(boolean... bools)`. Internally it calls Settings.getEnum
        json.put("pickupItemsMod", settings.getPickupItemsMod().name());

        // banBadRandomPickupItems
        json.put("banBadRandomPickupItems", settings.isBanBadRandomPickupItems());
    }
}
