package com.pkrandomizerweb;

import com.dabomstew.pkrandom.Settings;
import com.dabomstew.pkrandom.pokemon.GenRestrictions;
import org.json.JSONObject;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

/**
 * Generated by java-shim/generate-shim.mjs from settings-schema.json — do
 * not hand-edit. Reads a JSON settings payload (shaped by
 * settings-schema.json, produced by the web app's schema-driven form) and
 * calls the real {@link Settings} setters to build a Settings instance,
 * then writes it in the binary format {@code CliRandomizer} expects via
 * {@link Settings#write(FileOutputStream)}.
 *
 * Usage: java -cp PokeRandoZX.jar:settings-shim.jar com.pkrandomizerweb.SettingsBuilder <input.json> <output.rnqs>
 */
public class SettingsBuilder {

    public static void main(String[] args) {
        if (args.length != 2) {
            System.err.println("Usage: SettingsBuilder <input.json> <output.rnqs>");
            System.exit(1);
        }
        String inputJsonPath = args[0];
        String outputSettingsPath = args[1];

        try {
            String raw = new String(Files.readAllBytes(new File(inputJsonPath).toPath()), StandardCharsets.UTF_8);
            JSONObject json = new JSONObject(raw);

            Settings settings = new Settings();
            apply(settings, json);

            try (FileOutputStream out = new FileOutputStream(outputSettingsPath)) {
                settings.write(out);
            }
            System.out.println("Settings file written successfully.");
        } catch (IOException e) {
            System.err.println("ERROR: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } catch (RuntimeException e) {
            System.err.println("ERROR: invalid settings payload: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    private static void apply(Settings settings, JSONObject json) {
        // romName -- ROM display-name metadata written into the settings string; not itself a randomization toggle. Inclu
        settings.setRomName(json.optString("romName", ""));

        // currentRestrictions -- Takes a GenRestrictions object (see top-level 'genRestrictions' section). Only meaningful when limit
        {
            int genRestrictionsBits = 0;
            org.json.JSONObject genRestrictionsObj = json.optJSONObject("currentRestrictions");
            if (genRestrictionsObj != null) {
                if (genRestrictionsObj.optBoolean("allow_gen1", false)) genRestrictionsBits |= (1 << 0);
                if (genRestrictionsObj.optBoolean("allow_gen2", false)) genRestrictionsBits |= (1 << 1);
                if (genRestrictionsObj.optBoolean("allow_gen3", false)) genRestrictionsBits |= (1 << 2);
                if (genRestrictionsObj.optBoolean("allow_gen4", false)) genRestrictionsBits |= (1 << 3);
                if (genRestrictionsObj.optBoolean("allow_gen5", false)) genRestrictionsBits |= (1 << 4);
                if (genRestrictionsObj.optBoolean("allow_gen6", false)) genRestrictionsBits |= (1 << 5);
                if (genRestrictionsObj.optBoolean("allow_gen7", false)) genRestrictionsBits |= (1 << 6);
                if (genRestrictionsObj.optBoolean("allow_evolutionary_relatives", false)) genRestrictionsBits |= (1 << 7);
            }
            settings.setCurrentRestrictions(new GenRestrictions(genRestrictionsBits));
        }

        // currentMiscTweaks -- Takes an int bitmask. See top-level 'miscTweaks' section for each individual tweak's bit value; the 
        {
            int miscTweaksBits = 0;
            org.json.JSONArray miscTweaksArr = json.optJSONArray("currentMiscTweaks");
            if (miscTweaksArr != null) {
                for (int i = 0; i < miscTweaksArr.length(); i++) {
                    switch (miscTweaksArr.getString(i)) {
                        case "BW_EXP_PATCH": miscTweaksBits |= 1; break;
                        case "NERF_X_ACCURACY": miscTweaksBits |= 2; break;
                        case "FIX_CRIT_RATE": miscTweaksBits |= 4; break;
                        case "FASTEST_TEXT": miscTweaksBits |= 8; break;
                        case "RUNNING_SHOES_INDOORS": miscTweaksBits |= 16; break;
                        case "RANDOMIZE_PC_POTION": miscTweaksBits |= 32; break;
                        case "ALLOW_PIKACHU_EVOLUTION": miscTweaksBits |= 64; break;
                        case "NATIONAL_DEX_AT_START": miscTweaksBits |= 128; break;
                        case "UPDATE_TYPE_EFFECTIVENESS": miscTweaksBits |= 256; break;
                        case "FORCE_CHALLENGE_MODE": miscTweaksBits |= 512; break;
                        case "LOWER_CASE_POKEMON_NAMES": miscTweaksBits |= 1024; break;
                        case "RANDOMIZE_CATCHING_TUTORIAL": miscTweaksBits |= 2048; break;
                        case "BAN_LUCKY_EGG": miscTweaksBits |= 4096; break;
                        case "NO_FREE_LUCKY_EGG": miscTweaksBits |= 8192; break;
                        case "BAN_BIG_MANIAC_ITEMS": miscTweaksBits |= 16384; break;
                        case "SOS_BATTLES_FOR_ALL": miscTweaksBits |= 32768; break;
                        case "BALANCE_STATIC_LEVELS": miscTweaksBits |= 65536; break;
                        case "RETAIN_ALT_FORMES": miscTweaksBits |= 131072; break;
                        case "RUN_WITHOUT_RUNNING_SHOES": miscTweaksBits |= 262144; break;
                        case "FASTER_HP_AND_EXP_BARS": miscTweaksBits |= 524288; break;
                        case "FAST_DISTORTION_WORLD": miscTweaksBits |= 1048576; break;
                        case "UPDATE_ROTOM_FORME_TYPING": miscTweaksBits |= 2097152; break;
                        case "DISABLE_LOW_HP_MUSIC": miscTweaksBits |= 4194304; break;
                        default: break;
                    }
                }
            }
            settings.setCurrentMiscTweaks(miscTweaksBits);
        }

        // updateMoves -- Update move data (power/accuracy/PP/etc) to match a later generation's values, up to updateMovesToGe
        settings.setUpdateMoves(json.optBoolean("updateMoves", false));

        // updateMovesLegacy -- Legacy/older variant of the move-data-update feature, kept for backward compatibility with old setti
        settings.setUpdateMovesLegacy(json.optBoolean("updateMovesLegacy", false));

        // updateMovesToGeneration -- Generation number (e.g. 1-7) to update move data to; only relevant when updateMoves is true.
        settings.setUpdateMovesToGeneration(json.optInt("updateMovesToGeneration", 0));

        // dualTypeOnly
        settings.setDualTypeOnly(json.optBoolean("dualTypeOnly", false));

        // changeImpossibleEvolutions
        settings.setChangeImpossibleEvolutions(json.optBoolean("changeImpossibleEvolutions", false));

        // makeEvolutionsEasier
        settings.setMakeEvolutionsEasier(json.optBoolean("makeEvolutionsEasier", false));

        // removeTimeBasedEvolutions
        settings.setRemoveTimeBasedEvolutions(json.optBoolean("removeTimeBasedEvolutions", false));

        // evosAllowAltFormes -- Declared alongside the other Evolutions-tab fields in Settings.java, but its setter is interleaved w
        settings.setEvosAllowAltFormes(json.optBoolean("evosAllowAltFormes", false));

        // raceMode
        settings.setRaceMode(json.optBoolean("raceMode", false));

        // banIrregularAltFormes
        settings.setBanIrregularAltFormes(json.optBoolean("banIrregularAltFormes", false));

        // blockBrokenMoves -- Convenience setter: internally sets blockBrokenMovesetMoves, blockBrokenTMMoves, and blockBrokenTuto
        settings.setBlockBrokenMoves(json.optBoolean("blockBrokenMoves", false));

        // limitPokemon -- Enables the generation-restriction pool defined by currentRestrictions (GenRestrictions).
        settings.setLimitPokemon(json.optBoolean("limitPokemon", false));

        // baseStatisticsMod -- Java setter signature is `setBaseStatisticsMod(boolean... bools)`. Internally it calls Settings.getE
        {
            boolean[] baseStatisticsModBools = new boolean[Settings.BaseStatisticsMod.values().length];
            baseStatisticsModBools[Settings.BaseStatisticsMod.valueOf(json.optString("baseStatisticsMod", "UNCHANGED")).ordinal()] = true;
            settings.setBaseStatisticsMod(baseStatisticsModBools);
        }

        // baseStatsFollowEvolutions
        settings.setBaseStatsFollowEvolutions(json.optBoolean("baseStatsFollowEvolutions", false));

        // baseStatsFollowMegaEvolutions
        settings.setBaseStatsFollowMegaEvolutions(json.optBoolean("baseStatsFollowMegaEvolutions", false));

        // assignEvoStatsRandomly
        settings.setAssignEvoStatsRandomly(json.optBoolean("assignEvoStatsRandomly", false));

        // updateBaseStats
        settings.setUpdateBaseStats(json.optBoolean("updateBaseStats", false));

        // updateBaseStatsToGeneration -- Generation number to update base stats to; only relevant when updateBaseStats is true.
        settings.setUpdateBaseStatsToGeneration(json.optInt("updateBaseStatsToGeneration", 0));

        // standardizeEXPCurves
        settings.setStandardizeEXPCurves(json.optBoolean("standardizeEXPCurves", false));

        // selectedEXPCurve -- Takes the ExpCurve enum directly (not varargs booleans) - com.dabomstew.pkrandom.pokemon.ExpCurve, n
        settings.setSelectedEXPCurve(com.dabomstew.pkrandom.pokemon.ExpCurve.valueOf(json.optString("selectedEXPCurve", "SLOW")));

        // expCurveMod -- Controls which Pokemon (legendaries only / strong legendaries / all) get standardizeEXPCurves' selec
        {
            boolean[] expCurveModBools = new boolean[Settings.ExpCurveMod.values().length];
            expCurveModBools[Settings.ExpCurveMod.valueOf(json.optString("expCurveMod", "LEGENDARIES")).ordinal()] = true;
            settings.setExpCurveMod(expCurveModBools);
        }

        // abilitiesMod -- Java setter signature is `setAbilitiesMod(boolean... bools)`. Internally it calls Settings.getEnum(A
        {
            boolean[] abilitiesModBools = new boolean[Settings.AbilitiesMod.values().length];
            abilitiesModBools[Settings.AbilitiesMod.valueOf(json.optString("abilitiesMod", "UNCHANGED")).ordinal()] = true;
            settings.setAbilitiesMod(abilitiesModBools);
        }

        // allowWonderGuard
        settings.setAllowWonderGuard(json.optBoolean("allowWonderGuard", false));

        // abilitiesFollowEvolutions
        settings.setAbilitiesFollowEvolutions(json.optBoolean("abilitiesFollowEvolutions", false));

        // abilitiesFollowMegaEvolutions
        settings.setAbilitiesFollowMegaEvolutions(json.optBoolean("abilitiesFollowMegaEvolutions", false));

        // banTrappingAbilities
        settings.setBanTrappingAbilities(json.optBoolean("banTrappingAbilities", false));

        // banNegativeAbilities
        settings.setBanNegativeAbilities(json.optBoolean("banNegativeAbilities", false));

        // banBadAbilities
        settings.setBanBadAbilities(json.optBoolean("banBadAbilities", false));

        // weighDuplicateAbilitiesTogether
        settings.setWeighDuplicateAbilitiesTogether(json.optBoolean("weighDuplicateAbilitiesTogether", false));

        // ensureTwoAbilities
        settings.setEnsureTwoAbilities(json.optBoolean("ensureTwoAbilities", false));

        // startersMod -- Java setter signature is `setStartersMod(boolean... bools)`. Internally it calls Settings.getEnum(St
        {
            boolean[] startersModBools = new boolean[Settings.StartersMod.values().length];
            startersModBools[Settings.StartersMod.valueOf(json.optString("startersMod", "UNCHANGED")).ordinal()] = true;
            settings.setStartersMod(startersModBools);
        }

        // customStarters -- Takes int[3] (one 1-indexed Pokemon-list position per starter slot). Only relevant when startersMod 
        if (json.has("customStarters")) {
            org.json.JSONArray customStartersArr = json.getJSONArray("customStarters");
            int[] customStartersVals = new int[customStartersArr.length()];
            for (int i = 0; i < customStartersArr.length(); i++) customStartersVals[i] = customStartersArr.getInt(i);
            settings.setCustomStarters(customStartersVals);
        }

        // randomizeStartersHeldItems
        settings.setRandomizeStartersHeldItems(json.optBoolean("randomizeStartersHeldItems", false));

        // banBadRandomStarterHeldItems
        settings.setBanBadRandomStarterHeldItems(json.optBoolean("banBadRandomStarterHeldItems", false));

        // allowStarterAltFormes
        settings.setAllowStarterAltFormes(json.optBoolean("allowStarterAltFormes", false));

        // typesMod -- Java setter signature is `setTypesMod(boolean... bools)`. Internally it calls Settings.getEnum(Types
        {
            boolean[] typesModBools = new boolean[Settings.TypesMod.values().length];
            typesModBools[Settings.TypesMod.valueOf(json.optString("typesMod", "UNCHANGED")).ordinal()] = true;
            settings.setTypesMod(typesModBools);
        }

        // typesFollowMegaEvolutions
        settings.setTypesFollowMegaEvolutions(json.optBoolean("typesFollowMegaEvolutions", false));

        // evolutionsMod -- Java setter signature is `setEvolutionsMod(boolean... bools)`. Internally it calls Settings.getEnum(
        {
            boolean[] evolutionsModBools = new boolean[Settings.EvolutionsMod.values().length];
            evolutionsModBools[Settings.EvolutionsMod.valueOf(json.optString("evolutionsMod", "UNCHANGED")).ordinal()] = true;
            settings.setEvolutionsMod(evolutionsModBools);
        }

        // evosSimilarStrength
        settings.setEvosSimilarStrength(json.optBoolean("evosSimilarStrength", false));

        // evosSameTyping
        settings.setEvosSameTyping(json.optBoolean("evosSameTyping", false));

        // evosMaxThreeStages
        settings.setEvosMaxThreeStages(json.optBoolean("evosMaxThreeStages", false));

        // evosForceChange
        settings.setEvosForceChange(json.optBoolean("evosForceChange", false));

        // randomizeMovePowers
        settings.setRandomizeMovePowers(json.optBoolean("randomizeMovePowers", false));

        // randomizeMoveAccuracies
        settings.setRandomizeMoveAccuracies(json.optBoolean("randomizeMoveAccuracies", false));

        // randomizeMovePPs
        settings.setRandomizeMovePPs(json.optBoolean("randomizeMovePPs", false));

        // randomizeMoveTypes
        settings.setRandomizeMoveTypes(json.optBoolean("randomizeMoveTypes", false));

        // randomizeMoveCategory -- Only applicable to ROMs whose RomHandler reports hasPhysicalSpecialSplit() == true; the desktop app 
        settings.setRandomizeMoveCategory(json.optBoolean("randomizeMoveCategory", false));

        // movesetsMod -- Java setter signature is `setMovesetsMod(boolean... bools)`. Internally it calls Settings.getEnum(Mo
        {
            boolean[] movesetsModBools = new boolean[Settings.MovesetsMod.values().length];
            movesetsModBools[Settings.MovesetsMod.valueOf(json.optString("movesetsMod", "UNCHANGED")).ordinal()] = true;
            settings.setMovesetsMod(movesetsModBools);
        }

        // startWithGuaranteedMoves
        settings.setStartWithGuaranteedMoves(json.optBoolean("startWithGuaranteedMoves", false));

        // guaranteedMoveCount -- Number of guaranteed starting moves; GUI range is 2-4. Only relevant when startWithGuaranteedMoves i
        settings.setGuaranteedMoveCount(json.optInt("guaranteedMoveCount", 0));

        // reorderDamagingMoves
        settings.setReorderDamagingMoves(json.optBoolean("reorderDamagingMoves", false));

        // movesetsForceGoodDamaging
        settings.setMovesetsForceGoodDamaging(json.optBoolean("movesetsForceGoodDamaging", false));

        // movesetsGoodDamagingPercent -- Percent (0-100) of a Pokemon's moveset that should be 'good damaging' moves; only relevant when move
        settings.setMovesetsGoodDamagingPercent(json.optInt("movesetsGoodDamagingPercent", 0));

        // blockBrokenMovesetMoves -- Also settable in bulk via the General Options 'blockBrokenMoves' convenience setter.
        settings.setBlockBrokenMovesetMoves(json.optBoolean("blockBrokenMovesetMoves", false));

        // evolutionMovesForAll
        settings.setEvolutionMovesForAll(json.optBoolean("evolutionMovesForAll", false));

        // trainersMod -- Java setter signature is `setTrainersMod(boolean... bools)`. Internally it calls Settings.getEnum(Tr
        {
            boolean[] trainersModBools = new boolean[Settings.TrainersMod.values().length];
            trainersModBools[Settings.TrainersMod.valueOf(json.optString("trainersMod", "UNCHANGED")).ordinal()] = true;
            settings.setTrainersMod(trainersModBools);
        }

        // rivalCarriesStarterThroughout
        settings.setRivalCarriesStarterThroughout(json.optBoolean("rivalCarriesStarterThroughout", false));

        // trainersUsePokemonOfSimilarStrength
        settings.setTrainersUsePokemonOfSimilarStrength(json.optBoolean("trainersUsePokemonOfSimilarStrength", false));

        // trainersMatchTypingDistribution
        settings.setTrainersMatchTypingDistribution(json.optBoolean("trainersMatchTypingDistribution", false));

        // trainersBlockLegendaries
        settings.setTrainersBlockLegendaries(json.optBoolean("trainersBlockLegendaries", false));

        // trainersEnforceDistribution -- NOTE: Java setter uses a fluent/builder signature `public Settings setTrainersEnforceDistribution(bo
        settings.setTrainersEnforceDistribution(json.optBoolean("trainersEnforceDistribution", false));

        // trainersEnforceMainPlaythrough -- NOTE: Java setter uses a fluent/builder signature `public Settings setTrainersEnforceMainPlaythrough
        settings.setTrainersEnforceMainPlaythrough(json.optBoolean("trainersEnforceMainPlaythrough", false));

        // trainersBlockEarlyWonderGuard
        settings.setTrainersBlockEarlyWonderGuard(json.optBoolean("trainersBlockEarlyWonderGuard", false));

        // randomizeTrainerNames
        settings.setRandomizeTrainerNames(json.optBoolean("randomizeTrainerNames", false));

        // randomizeTrainerClassNames
        settings.setRandomizeTrainerClassNames(json.optBoolean("randomizeTrainerClassNames", false));

        // trainersForceFullyEvolved
        settings.setTrainersForceFullyEvolved(json.optBoolean("trainersForceFullyEvolved", false));

        // trainersForceFullyEvolvedLevel -- Minimum level threshold; only relevant when trainersForceFullyEvolved is true.
        settings.setTrainersForceFullyEvolvedLevel(json.optInt("trainersForceFullyEvolvedLevel", 0));

        // trainersLevelModified
        settings.setTrainersLevelModified(json.optBoolean("trainersLevelModified", false));

        // trainersLevelModifier -- Percent modifier, range -50..50. Only relevant when trainersLevelModified is true.
        settings.setTrainersLevelModifier(json.optInt("trainersLevelModifier", 0));

        // eliteFourUniquePokemonNumber -- Range 0-2 (packed into 3 bits alongside minimumCatchRateLevel in the settings byte format).
        settings.setEliteFourUniquePokemonNumber(json.optInt("eliteFourUniquePokemonNumber", 0));

        // allowTrainerAlternateFormes
        settings.setAllowTrainerAlternateFormes(json.optBoolean("allowTrainerAlternateFormes", false));

        // swapTrainerMegaEvos
        settings.setSwapTrainerMegaEvos(json.optBoolean("swapTrainerMegaEvos", false));

        // additionalBossTrainerPokemon -- Parameter name in Java is 'additional'. Number of extra Pokemon to add to boss trainers' teams.
        settings.setAdditionalBossTrainerPokemon(json.optInt("additionalBossTrainerPokemon", 0));

        // additionalImportantTrainerPokemon -- Parameter name in Java is 'additional'. Number of extra Pokemon to add to important trainers' teams.
        settings.setAdditionalImportantTrainerPokemon(json.optInt("additionalImportantTrainerPokemon", 0));

        // additionalRegularTrainerPokemon -- Parameter name in Java is 'additional'. Number of extra Pokemon to add to regular trainers' teams.
        settings.setAdditionalRegularTrainerPokemon(json.optInt("additionalRegularTrainerPokemon", 0));

        // randomizeHeldItemsForBossTrainerPokemon -- Java parameter name is 'bossTrainers'.
        settings.setRandomizeHeldItemsForBossTrainerPokemon(json.optBoolean("randomizeHeldItemsForBossTrainerPokemon", false));

        // randomizeHeldItemsForImportantTrainerPokemon -- Java parameter name is 'importantTrainers'.
        settings.setRandomizeHeldItemsForImportantTrainerPokemon(json.optBoolean("randomizeHeldItemsForImportantTrainerPokemon", false));

        // randomizeHeldItemsForRegularTrainerPokemon -- Java parameter name is 'regularTrainers'.
        settings.setRandomizeHeldItemsForRegularTrainerPokemon(json.optBoolean("randomizeHeldItemsForRegularTrainerPokemon", false));

        // consumableItemsOnlyForTrainerPokemon -- Field name (consumableItemsOnlyForTrainerPokemon) differs from the setter name (setConsumableItemsOn
        settings.setConsumableItemsOnlyForTrainers(json.optBoolean("consumableItemsOnlyForTrainerPokemon", false));

        // sensibleItemsOnlyForTrainerPokemon -- Field name (sensibleItemsOnlyForTrainerPokemon) differs from the setter name (setSensibleItemsOnlyFo
        settings.setSensibleItemsOnlyForTrainers(json.optBoolean("sensibleItemsOnlyForTrainerPokemon", false));

        // highestLevelOnlyGetsItemsForTrainerPokemon -- Field name (highestLevelOnlyGetsItemsForTrainerPokemon) differs from the setter name (setHighestLeve
        settings.setHighestLevelGetsItemsForTrainers(json.optBoolean("highestLevelOnlyGetsItemsForTrainerPokemon", false));

        // doubleBattleMode
        settings.setDoubleBattleMode(json.optBoolean("doubleBattleMode", false));

        // shinyChance -- Despite the boolean type this represents an 'increased shiny chance' toggle, not a literal chance va
        settings.setShinyChance(json.optBoolean("shinyChance", false));

        // betterTrainerMovesets
        settings.setBetterTrainerMovesets(json.optBoolean("betterTrainerMovesets", false));

        // wildPokemonMod -- Java setter signature is `setWildPokemonMod(boolean... bools)`. Internally it calls Settings.getEnum
        {
            boolean[] wildPokemonModBools = new boolean[Settings.WildPokemonMod.values().length];
            wildPokemonModBools[Settings.WildPokemonMod.valueOf(json.optString("wildPokemonMod", "UNCHANGED")).ordinal()] = true;
            settings.setWildPokemonMod(wildPokemonModBools);
        }

        // wildPokemonRestrictionMod -- Java setter signature is `setWildPokemonRestrictionMod(boolean... bools)`. Internally it calls Setti
        {
            boolean[] wildPokemonRestrictionModBools = new boolean[Settings.WildPokemonRestrictionMod.values().length];
            wildPokemonRestrictionModBools[Settings.WildPokemonRestrictionMod.valueOf(json.optString("wildPokemonRestrictionMod", "NONE")).ordinal()] = true;
            settings.setWildPokemonRestrictionMod(wildPokemonRestrictionModBools);
        }

        // useTimeBasedEncounters
        settings.setUseTimeBasedEncounters(json.optBoolean("useTimeBasedEncounters", false));

        // blockWildLegendaries
        settings.setBlockWildLegendaries(json.optBoolean("blockWildLegendaries", false));

        // useMinimumCatchRate
        settings.setUseMinimumCatchRate(json.optBoolean("useMinimumCatchRate", false));

        // minimumCatchRateLevel -- Range roughly 1-5 (GUI slider); only relevant when useMinimumCatchRate is true.
        settings.setMinimumCatchRateLevel(json.optInt("minimumCatchRateLevel", 0));

        // randomizeWildPokemonHeldItems
        settings.setRandomizeWildPokemonHeldItems(json.optBoolean("randomizeWildPokemonHeldItems", false));

        // banBadRandomWildPokemonHeldItems
        settings.setBanBadRandomWildPokemonHeldItems(json.optBoolean("banBadRandomWildPokemonHeldItems", false));

        // balanceShakingGrass
        settings.setBalanceShakingGrass(json.optBoolean("balanceShakingGrass", false));

        // wildLevelsModified
        settings.setWildLevelsModified(json.optBoolean("wildLevelsModified", false));

        // wildLevelModifier -- Percent modifier, range -50..50. Only relevant when wildLevelsModified is true.
        settings.setWildLevelModifier(json.optInt("wildLevelModifier", 0));

        // allowWildAltFormes
        settings.setAllowWildAltFormes(json.optBoolean("allowWildAltFormes", false));

        // staticPokemonMod -- Java setter signature is `setStaticPokemonMod(boolean... bools)`. Internally it calls Settings.getEn
        {
            boolean[] staticPokemonModBools = new boolean[Settings.StaticPokemonMod.values().length];
            staticPokemonModBools[Settings.StaticPokemonMod.valueOf(json.optString("staticPokemonMod", "UNCHANGED")).ordinal()] = true;
            settings.setStaticPokemonMod(staticPokemonModBools);
        }

        // limitMainGameLegendaries -- Field is declared in Settings.java alongside the Starter Pokemon fields, but its setter is placed in
        settings.setLimitMainGameLegendaries(json.optBoolean("limitMainGameLegendaries", false));

        // limit600 -- Field is declared in Settings.java alongside the Starter Pokemon fields, but its setter is placed in
        settings.setLimit600(json.optBoolean("limit600", false));

        // allowStaticAltFormes
        settings.setAllowStaticAltFormes(json.optBoolean("allowStaticAltFormes", false));

        // swapStaticMegaEvos
        settings.setSwapStaticMegaEvos(json.optBoolean("swapStaticMegaEvos", false));

        // staticLevelModified
        settings.setStaticLevelModified(json.optBoolean("staticLevelModified", false));

        // staticLevelModifier -- Percent modifier, range -50..50. Only relevant when staticLevelModified is true.
        settings.setStaticLevelModifier(json.optInt("staticLevelModifier", 0));

        // correctStaticMusic
        settings.setCorrectStaticMusic(json.optBoolean("correctStaticMusic", false));

        // totemPokemonMod -- Totem Pokemon only exist in Gen 7 (Sun/Moon/Ultra Sun/Ultra Moon) ROMs. Java setter signature is `se
        {
            boolean[] totemPokemonModBools = new boolean[Settings.TotemPokemonMod.values().length];
            totemPokemonModBools[Settings.TotemPokemonMod.valueOf(json.optString("totemPokemonMod", "UNCHANGED")).ordinal()] = true;
            settings.setTotemPokemonMod(totemPokemonModBools);
        }

        // allyPokemonMod -- Controls the ally Pokemon that assist Totem Pokemon in battle. Java setter signature is `setAllyPoke
        {
            boolean[] allyPokemonModBools = new boolean[Settings.AllyPokemonMod.values().length];
            allyPokemonModBools[Settings.AllyPokemonMod.valueOf(json.optString("allyPokemonMod", "UNCHANGED")).ordinal()] = true;
            settings.setAllyPokemonMod(allyPokemonModBools);
        }

        // auraMod -- Controls the aura effect Totem Pokemon apply in battle. Java setter signature is `setAuraMod(boolean
        {
            boolean[] auraModBools = new boolean[Settings.AuraMod.values().length];
            auraModBools[Settings.AuraMod.valueOf(json.optString("auraMod", "UNCHANGED")).ordinal()] = true;
            settings.setAuraMod(auraModBools);
        }

        // randomizeTotemHeldItems
        settings.setRandomizeTotemHeldItems(json.optBoolean("randomizeTotemHeldItems", false));

        // totemLevelsModified
        settings.setTotemLevelsModified(json.optBoolean("totemLevelsModified", false));

        // totemLevelModifier -- Percent modifier, range -50..50. Only relevant when totemLevelsModified is true.
        settings.setTotemLevelModifier(json.optInt("totemLevelModifier", 0));

        // allowTotemAltFormes
        settings.setAllowTotemAltFormes(json.optBoolean("allowTotemAltFormes", false));

        // tmsMod -- Java setter signature is `setTmsMod(boolean... bools)`. Internally it calls Settings.getEnum(TMsMod.
        {
            boolean[] tmsModBools = new boolean[Settings.TMsMod.values().length];
            tmsModBools[Settings.TMsMod.valueOf(json.optString("tmsMod", "UNCHANGED")).ordinal()] = true;
            settings.setTmsMod(tmsModBools);
        }

        // tmLevelUpMoveSanity
        settings.setTmLevelUpMoveSanity(json.optBoolean("tmLevelUpMoveSanity", false));

        // keepFieldMoveTMs
        settings.setKeepFieldMoveTMs(json.optBoolean("keepFieldMoveTMs", false));

        // fullHMCompat
        settings.setFullHMCompat(json.optBoolean("fullHMCompat", false));

        // tmsForceGoodDamaging
        settings.setTmsForceGoodDamaging(json.optBoolean("tmsForceGoodDamaging", false));

        // tmsGoodDamagingPercent -- Percent (0-100); only relevant when tmsForceGoodDamaging is true.
        settings.setTmsGoodDamagingPercent(json.optInt("tmsGoodDamagingPercent", 0));

        // blockBrokenTMMoves -- Also settable in bulk via the General Options 'blockBrokenMoves' convenience setter.
        settings.setBlockBrokenTMMoves(json.optBoolean("blockBrokenTMMoves", false));

        // tmsHmsCompatibilityMod -- Java setter signature is `setTmsHmsCompatibilityMod(boolean... bools)`. Internally it calls Settings
        {
            boolean[] tmsHmsCompatibilityModBools = new boolean[Settings.TMsHMsCompatibilityMod.values().length];
            tmsHmsCompatibilityModBools[Settings.TMsHMsCompatibilityMod.valueOf(json.optString("tmsHmsCompatibilityMod", "UNCHANGED")).ordinal()] = true;
            settings.setTmsHmsCompatibilityMod(tmsHmsCompatibilityModBools);
        }

        // tmsFollowEvolutions
        settings.setTmsFollowEvolutions(json.optBoolean("tmsFollowEvolutions", false));

        // moveTutorMovesMod -- Only applicable to ROMs that support move tutors (Gen 3 Emerald/FRLG onward). Java setter signature 
        {
            boolean[] moveTutorMovesModBools = new boolean[Settings.MoveTutorMovesMod.values().length];
            moveTutorMovesModBools[Settings.MoveTutorMovesMod.valueOf(json.optString("moveTutorMovesMod", "UNCHANGED")).ordinal()] = true;
            settings.setMoveTutorMovesMod(moveTutorMovesModBools);
        }

        // tutorLevelUpMoveSanity
        settings.setTutorLevelUpMoveSanity(json.optBoolean("tutorLevelUpMoveSanity", false));

        // keepFieldMoveTutors
        settings.setKeepFieldMoveTutors(json.optBoolean("keepFieldMoveTutors", false));

        // tutorsForceGoodDamaging
        settings.setTutorsForceGoodDamaging(json.optBoolean("tutorsForceGoodDamaging", false));

        // tutorsGoodDamagingPercent -- Percent (0-100); only relevant when tutorsForceGoodDamaging is true.
        settings.setTutorsGoodDamagingPercent(json.optInt("tutorsGoodDamagingPercent", 0));

        // blockBrokenTutorMoves -- Also settable in bulk via the General Options 'blockBrokenMoves' convenience setter.
        settings.setBlockBrokenTutorMoves(json.optBoolean("blockBrokenTutorMoves", false));

        // moveTutorsCompatibilityMod -- Java setter signature is `setMoveTutorsCompatibilityMod(boolean... bools)`. Internally it calls Sett
        {
            boolean[] moveTutorsCompatibilityModBools = new boolean[Settings.MoveTutorsCompatibilityMod.values().length];
            moveTutorsCompatibilityModBools[Settings.MoveTutorsCompatibilityMod.valueOf(json.optString("moveTutorsCompatibilityMod", "UNCHANGED")).ordinal()] = true;
            settings.setMoveTutorsCompatibilityMod(moveTutorsCompatibilityModBools);
        }

        // tutorFollowEvolutions
        settings.setTutorFollowEvolutions(json.optBoolean("tutorFollowEvolutions", false));

        // inGameTradesMod -- Java setter signature is `setInGameTradesMod(boolean... bools)`. Internally it calls Settings.getEnu
        {
            boolean[] inGameTradesModBools = new boolean[Settings.InGameTradesMod.values().length];
            inGameTradesModBools[Settings.InGameTradesMod.valueOf(json.optString("inGameTradesMod", "UNCHANGED")).ordinal()] = true;
            settings.setInGameTradesMod(inGameTradesModBools);
        }

        // randomizeInGameTradesNicknames
        settings.setRandomizeInGameTradesNicknames(json.optBoolean("randomizeInGameTradesNicknames", false));

        // randomizeInGameTradesOTs
        settings.setRandomizeInGameTradesOTs(json.optBoolean("randomizeInGameTradesOTs", false));

        // randomizeInGameTradesIVs
        settings.setRandomizeInGameTradesIVs(json.optBoolean("randomizeInGameTradesIVs", false));

        // randomizeInGameTradesItems
        settings.setRandomizeInGameTradesItems(json.optBoolean("randomizeInGameTradesItems", false));

        // fieldItemsMod -- Java setter signature is `setFieldItemsMod(boolean... bools)`. Internally it calls Settings.getEnum(
        {
            boolean[] fieldItemsModBools = new boolean[Settings.FieldItemsMod.values().length];
            fieldItemsModBools[Settings.FieldItemsMod.valueOf(json.optString("fieldItemsMod", "UNCHANGED")).ordinal()] = true;
            settings.setFieldItemsMod(fieldItemsModBools);
        }

        // banBadRandomFieldItems
        settings.setBanBadRandomFieldItems(json.optBoolean("banBadRandomFieldItems", false));

        // shopItemsMod -- Java setter signature is `setShopItemsMod(boolean... bools)`. Internally it calls Settings.getEnum(S
        {
            boolean[] shopItemsModBools = new boolean[Settings.ShopItemsMod.values().length];
            shopItemsModBools[Settings.ShopItemsMod.valueOf(json.optString("shopItemsMod", "UNCHANGED")).ordinal()] = true;
            settings.setShopItemsMod(shopItemsModBools);
        }

        // banBadRandomShopItems
        settings.setBanBadRandomShopItems(json.optBoolean("banBadRandomShopItems", false));

        // banRegularShopItems
        settings.setBanRegularShopItems(json.optBoolean("banRegularShopItems", false));

        // banOPShopItems
        settings.setBanOPShopItems(json.optBoolean("banOPShopItems", false));

        // balanceShopPrices
        settings.setBalanceShopPrices(json.optBoolean("balanceShopPrices", false));

        // guaranteeEvolutionItems
        settings.setGuaranteeEvolutionItems(json.optBoolean("guaranteeEvolutionItems", false));

        // guaranteeXItems
        settings.setGuaranteeXItems(json.optBoolean("guaranteeXItems", false));

        // pickupItemsMod -- Java setter signature is `setPickupItemsMod(boolean... bools)`. Internally it calls Settings.getEnum
        {
            boolean[] pickupItemsModBools = new boolean[Settings.PickupItemsMod.values().length];
            pickupItemsModBools[Settings.PickupItemsMod.valueOf(json.optString("pickupItemsMod", "UNCHANGED")).ordinal()] = true;
            settings.setPickupItemsMod(pickupItemsModBools);
        }

        // banBadRandomPickupItems
        settings.setBanBadRandomPickupItems(json.optBoolean("banBadRandomPickupItems", false));
    }
}
